### ISSUE TITLE
Cable image should include Pandoc for ingesting Word documents

### ISSUE THREAD

**Issue by nepella** [ManifoldScholar/manifold-docker-build#17]
The containerized version of Manifold fails to ingest Microsoft Word XML documents ("DOCX" files), complaining that "No Strategy [could be] found" for an uploaded file. This appears to be caused be the check for Pandoc in [`ms_word.rb`](/ManifoldScholar/manifold/blob/5d20fdc550fd47465edc70ec5e8d63ddbf461e4f/api/app/services/ingestions/converters/ms_word.rb#L14) failing because Pandoc is not installed. If I execute `apt install -y pandoc` inside the running Cable container, a subsequent DOCX ingestion succeeds. Can Pandoc be added to the image?

**Comment by zdavis** [comment]
Starting with v6, due out any day, Manifold is uses Mammoth instead of Pandoc for word ingestion, so I'm going to go ahead and close this.
